@startuml
'https://plantuml.com/use-case-diagram

:Admin: as ADM
:Unknows user: as UUSR
:User: as USR
:Employee: as EMP

package "Chat" {
    (Chat) as (CHT)
    (Request Support) as (RS)
    (Give Support) as (GS)

    (CHT) .-> (GS):include
    (CHT) .-> (RS):include
}

package "Tickets" {
    (View created tickets) as (VCT)
    (Create ticket) as (CT)
    (Edit ticket) as (ET)
    (Submit ticket) as (ST)
    (Delete ticket) as (DT)
    (Upload attachment) as (UA)

    (Download attachment) as (DA)

    (View submitted tickets) as (VST)
    (Assign ticket) as (AT)
    (Close ticket) as (CST)

    (View ticket) as (VT)

    (VCT) .> (VT):include
    (VST) .> (VT):include
}

package "Administration" {
    (Register) as (REG)
    (Create user) as (UCRT)
    (Change password) as (CP)

    (UCRT) <|-- (REG)
}


left to right direction

USR -> (VCT) #line:red
USR -> (CT) #line:red
USR -> (ET)#line:red
USR -> (ST)#line:red
USR -> (DT)#line:red
USR -> (UA)#line:red

USR --> (DA)#line:red
EMP --> (DA)#line:green
USR -left-> (CP)#line:red
EMP -left-> (CP)#line:green

EMP --> (VST)#line:green
EMP --> (AT)#line:green
EMP --> (CST)#line:green

(UCRT) <-- ADM #line:blue
(CP) <-- ADM #line:blue
(REG) <-- UUSR

USR -up-> (RS)#line:red
EMP -up-> (GS)#line:green

'following instructions are for positioning
"Chat" -[hidden]-> "Administration"
"Chat" -[hidden]-> "Administration"
"Chat" -[hidden]-> "Administration"
UUSR -[hidden]- (CST)

@enduml