@startuml

interface ServerSocketFactory {
    createServerSocket()
}

class DefaultServerSocketFactory {
    createServerSocket()
}

class UserImplementedSSF {
    createServerSocket()
}
ServerSocketFactory <|-- DefaultServerSocketFactory
ServerSocketFactory <|-- UserImplementedSSF
@enduml