@startuml
:User: as U
(Accepting Thread) as T
(Connection Thread) as CT
(Thread Pool) as TP

U -> T: ConnectionRequest
T --> TP: Accepted connection
TP --> CT: demand to thread
U -> CT: requests
CT -> U: Responses
@enduml